package memory

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

// The file plane projects memory into two bounded markdown files per cluster:
// CLUSTER.md (recent known state) and MEMORY.md (themes and recurring resolutions).
// They give a human or a file native agent a cheap, greppable read of what the
// system knows. Files are a projection; the database is the source of truth.

const (
	DefaultFilePlaneBytes = 25_000
	projectionNote        = "_Projection — the database is the source of truth; this file is regenerated by the consolidation worker._"
	truncMarker           = "\n…[truncated to fit the ≤25KB file-plane budget]"
)

// boundBytes caps text to maxBytes on a line boundary, never mid line and never silently.
func boundBytes(text string, maxBytes int) string {
	if len(text) <= maxBytes {
		return text
	}
	budget := maxBytes - len(truncMarker)
	if budget < 0 {
		budget = 0
	}
	cut := text[:budget]
	for len(cut) > 0 && !validEnd(cut) {
		cut = cut[:len(cut)-1]
	}
	if i := strings.LastIndex(cut, "\n"); i > 0 {
		cut = cut[:i]
	}
	return strings.TrimRight(cut, " \t\r\n") + truncMarker
}

// validEnd is true when s does not end in the middle of a UTF-8 sequence.
func validEnd(s string) bool {
	for i := len(s) - 1; i >= 0 && i >= len(s)-4; i-- {
		b := s[i]
		if b < 0x80 {
			return true
		}
		if b >= 0xC0 { // a lead byte: complete only if its continuation bytes are all here
			need := 2
			switch {
			case b >= 0xF0:
				need = 4
			case b >= 0xE0:
				need = 3
			}
			return len(s)-i >= need
		}
	}
	return true
}

// FileEpisode is the slice of an episode the projections show.
type FileEpisode struct {
	Namespace, Outcome, Summary, RootCause string
	Verified                               bool
}

// RenderClusterMD projects recent known cluster state to markdown.
func RenderClusterMD(cluster string, eps []FileEpisode, maxBytes int) string {
	lines := []string{"# CLUSTER.md — " + cluster, "", projectionNote, ""}
	seen := map[string]bool{}
	var ns []string
	for _, e := range eps {
		if e.Namespace != "" && !seen[e.Namespace] {
			seen[e.Namespace] = true
			ns = append(ns, e.Namespace)
		}
	}
	sortStrings(ns)
	if len(ns) > 0 {
		lines = append(lines, "## Namespaces seen")
		for _, n := range ns {
			lines = append(lines, "- "+n)
		}
		lines = append(lines, "")
	}
	lines = append(lines, "## Recent episodes")
	if len(eps) == 0 {
		lines = append(lines, "_none recorded yet_")
	}
	for _, e := range eps {
		outcome := e.Outcome
		if outcome == "" {
			outcome = "report_only"
		}
		lines = append(lines, fmt.Sprintf("- [%s] %s", outcome, clip(strings.ReplaceAll(e.Summary, "\n", " "), 200)))
	}
	return boundBytes(strings.Join(lines, "\n"), maxBytes)
}

// RenderMemoryMD projects the learned memory digest to markdown.
func RenderMemoryMD(cluster, themes string, eps []FileEpisode, maxBytes int) string {
	lines := []string{"# MEMORY.md — " + cluster, "", projectionNote, ""}
	if strings.TrimSpace(themes) != "" {
		lines = append(lines, strings.TrimSpace(themes), "")
	}
	lines = append(lines, "## Recurring resolutions")
	n := 0
	for _, e := range eps {
		if e.Verified && e.RootCause != "" {
			n++
			lines = append(lines, fmt.Sprintf("- **%s** — %s", clip(e.RootCause, 160), clip(strings.ReplaceAll(e.Summary, "\n", " "), 160)))
		}
	}
	if n == 0 {
		lines = append(lines, "_no verified resolutions yet_")
	}
	return boundBytes(strings.Join(lines, "\n"), maxBytes)
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// RegenerateFilePlane writes CLUSTER.md and MEMORY.md for a cluster into dir and
// returns the bytes written. It never fails the consolidation pass: a failure is
// registered and reads as zero bytes.
func (s *Store) RegenerateFilePlane(ctx context.Context, cluster, dir string, maxBytes int) int {
	recalled, err := s.RecallEpisodes(ctx, "incident failure error outage", cluster, 15)
	if err != nil {
		slog.Warn("file plane could not read episodes", "err", err)
		s.Live.RecordPassFailure("file_plane_bytes", err)
		return 0
	}
	sums, err := s.RecallThemeSummaries(ctx, "incident", cluster, 5)
	if err != nil {
		slog.Warn("file plane could not read themes", "err", err)
		s.Live.RecordPassFailure("file_plane_bytes", err)
		return 0
	}
	eps := make([]FileEpisode, len(recalled))
	for i, r := range recalled {
		eps[i] = FileEpisode{Namespace: r.Namespace, Outcome: r.Outcome, Summary: r.Summary, RootCause: r.RootCause, Verified: r.Verified}
	}
	cluster1, memory1 := RenderClusterMD(cluster, eps, maxBytes), RenderMemoryMD(cluster, RenderSummariesBlock(sums), eps, maxBytes)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		slog.Warn("file plane could not create its directory", "err", err)
		s.Live.RecordPassFailure("file_plane_bytes", err)
		return 0
	}
	for name, body := range map[string]string{"CLUSTER.md": cluster1, "MEMORY.md": memory1} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			slog.Warn("file plane write failed", "file", name, "err", err)
			s.Live.RecordPassFailure("file_plane_bytes", err)
			return 0
		}
	}
	return len(cluster1) + len(memory1)
}
